create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  lead_id text unique,
  nome text,
  name text,
  email text,
  telefone text,
  stage text not null default 'novo',
  origem text,
  interesse_produto text,
  cidade text,
  cep text,
  ultima_mensagem text,
  ai_enabled boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_update timestamptz not null default now()
);

create index if not exists idx_leads_lead_id on public.leads (lead_id);
create index if not exists idx_leads_stage on public.leads (stage);
create index if not exists idx_leads_last_update on public.leads (last_update desc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  lead_ref bigint,
  lead_id text,
  message_id text,
  nome text,
  direction text,
  sender text,
  sender_type text,
  role text,
  status text,
  texto text,
  text text,
  mensagem text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_messages_lead_ref on public.messages (lead_ref);
create index if not exists idx_messages_lead_id on public.messages (lead_id);
create index if not exists idx_messages_created_at on public.messages (created_at desc);
