-- Campaign delivery 1: operational imports, scoped consent, immutable campaign
-- revisions and an explicit per-campaign recipient projection.
--
-- This is expand-first. Existing conversation/outbox behavior remains valid and
-- no imported batch is projected into the Knowledge Graph.

ALTER TABLE public.audiences
  ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE public.audiences
SET metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
  'kind', CASE
    WHEN source_type = 'import' OR slug = 'import' THEN 'legacy_import_bucket'
    ELSE 'semantic_group'
  END
)
WHERE NOT (COALESCE(metadata, '{}'::jsonb) ? 'kind');

-- The graph bridge already writes source_type=graph. Historical installations
-- may still carry the narrower check created by migration 020.
ALTER TABLE public.audiences DROP CONSTRAINT IF EXISTS audiences_source_type_check;
ALTER TABLE public.audiences
  ADD CONSTRAINT audiences_source_type_check
  CHECK (source_type IN ('manual', 'import', 'crm', 'shared', 'graph'));

ALTER TABLE public.campaigns
  ADD COLUMN IF NOT EXISTS campaign_kind text,
  ADD COLUMN IF NOT EXISTS purpose text,
  ADD COLUMN IF NOT EXISTS channel text,
  ADD COLUMN IF NOT EXISTS provider text,
  ADD COLUMN IF NOT EXISTS audience_id uuid REFERENCES public.audiences(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS current_revision integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS idempotency_key text,
  ADD COLUMN IF NOT EXISTS reason text,
  ADD COLUMN IF NOT EXISTS created_by_user_id uuid REFERENCES public.app_users(id) ON DELETE SET NULL;

UPDATE public.campaigns
SET metadata = COALESCE(metadata, '{}'::jsonb) || '{"kind":"knowledge_legacy"}'::jsonb
WHERE campaign_kind IS NULL
  AND COALESCE(metadata->>'kind', '') = '';

ALTER TABLE public.campaigns DROP CONSTRAINT IF EXISTS campaigns_status_check;

ALTER TABLE public.campaigns
  ADD CONSTRAINT campaigns_status_check CHECK (status IN (
    'draft', 'validated', 'scheduled', 'running', 'paused',
    'completed', 'cancelled', 'failed', 'active', 'finished'
  ));

ALTER TABLE public.campaigns
  ADD CONSTRAINT campaigns_kind_check
  CHECK (campaign_kind IS NULL OR campaign_kind IN ('consent_request', 'promotional'));

CREATE UNIQUE INDEX IF NOT EXISTS idx_campaigns_idempotency
  ON public.campaigns(idempotency_key)
  WHERE idempotency_key IS NOT NULL AND idempotency_key <> '';
CREATE INDEX IF NOT EXISTS idx_campaigns_persona_status_created
  ON public.campaigns(persona_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.lead_import_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_id uuid NOT NULL REFERENCES public.personas(id) ON DELETE CASCADE,
  audience_id uuid REFERENCES public.audiences(id) ON DELETE SET NULL,
  filename text NOT NULL,
  file_checksum text NOT NULL,
  source text NOT NULL DEFAULT 'csv_upload',
  contact_basis text NOT NULL DEFAULT 'unknown' CHECK (contact_basis IN (
    'explicit_consent', 'customer_initiated', 'existing_customer',
    'imported_without_evidence', 'legacy_unknown', 'unknown'
  )),
  status text NOT NULL DEFAULT 'processing' CHECK (status IN ('processing', 'completed', 'failed', 'archived')),
  total_rows integer NOT NULL DEFAULT 0 CHECK (total_rows >= 0),
  valid_rows integer NOT NULL DEFAULT 0 CHECK (valid_rows >= 0),
  phone_rows integer NOT NULL DEFAULT 0 CHECK (phone_rows >= 0),
  email_only_rows integer NOT NULL DEFAULT 0 CHECK (email_only_rows >= 0),
  created_leads integer NOT NULL DEFAULT 0 CHECK (created_leads >= 0),
  updated_leads integer NOT NULL DEFAULT 0 CHECK (updated_leads >= 0),
  invalid_rows integer NOT NULL DEFAULT 0 CHECK (invalid_rows >= 0),
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  error text,
  created_by_user_id uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  archived_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_import_batches_persona_created
  ON public.lead_import_batches(persona_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_import_batches_audience
  ON public.lead_import_batches(audience_id, created_at DESC)
  WHERE audience_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.lead_import_rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id uuid NOT NULL REFERENCES public.lead_import_batches(id) ON DELETE CASCADE,
  persona_id uuid NOT NULL REFERENCES public.personas(id) ON DELETE CASCADE,
  row_index integer NOT NULL CHECK (row_index > 0),
  lead_id bigint REFERENCES public.leads(id) ON DELETE SET NULL,
  status text NOT NULL CHECK (status IN ('created', 'updated', 'email_only', 'invalid')),
  error_code text,
  parsed_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (batch_id, row_index)
);

CREATE INDEX IF NOT EXISTS idx_lead_import_rows_batch_lead
  ON public.lead_import_rows(batch_id, lead_id)
  WHERE lead_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_lead_import_rows_persona_lead
  ON public.lead_import_rows(persona_id, lead_id)
  WHERE lead_id IS NOT NULL;

-- Conservative shadow backfill: retain only parsed operational fields. The
-- historical raw_row (which may contain arbitrary PII) is intentionally not
-- copied into the new projection.
INSERT INTO public.lead_import_batches (
  id, persona_id, filename, file_checksum, source, contact_basis, status,
  total_rows, valid_rows, phone_rows, email_only_rows, created_leads,
  updated_leads, invalid_rows, provenance, error, created_at, completed_at, updated_at
)
SELECT DISTINCT ON ((e.payload->>'batch_id'))
  (e.payload->>'batch_id')::uuid,
  e.persona_id,
  COALESCE(e.payload->>'filename', 'legacy-import.csv'),
  'sha256:legacy-unknown-' || (e.payload->>'batch_id'),
  'legacy_system_events',
  'legacy_unknown',
  CASE WHEN e.payload->>'status' = 'completed' THEN 'completed' ELSE 'failed' END,
  CASE WHEN COALESCE(e.payload->'stats'->>'total', '') ~ '^[0-9]+$'
    THEN (e.payload->'stats'->>'total')::integer ELSE 0 END,
  CASE WHEN COALESCE(e.payload->'stats'->>'valid', '') ~ '^[0-9]+$'
    THEN (e.payload->'stats'->>'valid')::integer ELSE 0 END,
  CASE WHEN COALESCE(e.payload->'stats'->>'with_phone', '') ~ '^[0-9]+$'
    THEN (e.payload->'stats'->>'with_phone')::integer ELSE 0 END,
  CASE WHEN COALESCE(e.payload->'stats'->>'email_only', '') ~ '^[0-9]+$'
    THEN (e.payload->'stats'->>'email_only')::integer ELSE 0 END,
  CASE WHEN COALESCE(e.payload->'stats'->>'created', '') ~ '^[0-9]+$'
    THEN (e.payload->'stats'->>'created')::integer ELSE 0 END,
  CASE WHEN COALESCE(e.payload->'stats'->>'updated', '') ~ '^[0-9]+$'
    THEN (e.payload->'stats'->>'updated')::integer ELSE 0 END,
  CASE WHEN COALESCE(e.payload->'stats'->>'invalid', '') ~ '^[0-9]+$'
    THEN (e.payload->'stats'->>'invalid')::integer ELSE 0 END,
  jsonb_build_object('legacy_event_id', e.id, 'headers', COALESCE(e.payload->'headers', '[]'::jsonb)),
  e.payload->>'error',
  e.created_at,
  e.created_at,
  e.created_at
FROM public.system_events e
WHERE e.event_type = 'lead_import_batch'
  AND e.persona_id IS NOT NULL
  AND COALESCE(e.payload->>'batch_id', '') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
ORDER BY (e.payload->>'batch_id'), e.created_at DESC
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.lead_import_rows (
  batch_id, persona_id, row_index, lead_id, status, error_code, parsed_data, created_at
)
SELECT
  (e.payload->>'batch_id')::uuid,
  e.persona_id,
  CASE WHEN COALESCE(e.payload->>'row_index', '') ~ '^[1-9][0-9]*$'
    THEN (e.payload->>'row_index')::integer ELSE 1 END,
  CASE WHEN COALESCE(e.payload->>'lead_ref', '') ~ '^[0-9]+$'
    THEN (e.payload->>'lead_ref')::bigint ELSE NULL END,
  CASE WHEN e.payload->>'status' IN ('created', 'updated', 'email_only', 'invalid')
    THEN e.payload->>'status' ELSE 'invalid' END,
  NULLIF(e.payload->>'error', ''),
  COALESCE(e.payload->'parsed', '{}'::jsonb),
  e.created_at
FROM public.system_events e
JOIN public.lead_import_batches b ON b.id::text = e.payload->>'batch_id'
WHERE e.event_type = 'lead_import_row'
  AND e.persona_id IS NOT NULL
  AND COALESCE(e.payload->>'batch_id', '') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
ON CONFLICT (batch_id, row_index) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.contact_consents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id bigint NOT NULL REFERENCES public.leads(id) ON DELETE RESTRICT,
  persona_id uuid NOT NULL REFERENCES public.personas(id) ON DELETE RESTRICT,
  channel text NOT NULL,
  purpose text NOT NULL,
  communication_category text,
  status text NOT NULL CHECK (status IN ('pending', 'granted', 'refused', 'revoked', 'review_required')),
  source text NOT NULL,
  request_message_id bigint REFERENCES public.messages(id) ON DELETE SET NULL,
  response_message_id bigint REFERENCES public.messages(id) ON DELETE SET NULL,
  campaign_id uuid REFERENCES public.campaigns(id) ON DELETE SET NULL,
  import_batch_id uuid REFERENCES public.lead_import_batches(id) ON DELETE SET NULL,
  effective_at timestamptz NOT NULL DEFAULT now(),
  granted_at timestamptz,
  revoked_at timestamptz,
  valid_until timestamptz,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor_user_id uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  idempotency_key text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (btrim(channel) <> ''),
  CHECK (btrim(purpose) <> ''),
  CHECK (btrim(source) <> ''),
  CHECK (valid_until IS NULL OR valid_until > effective_at),
  CHECK (status <> 'granted' OR granted_at IS NOT NULL),
  CHECK (status <> 'revoked' OR revoked_at IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_contact_consents_scope_latest
  ON public.contact_consents(persona_id, lead_id, channel, purpose, effective_at DESC);
CREATE INDEX IF NOT EXISTS idx_contact_consents_campaign
  ON public.contact_consents(campaign_id, effective_at DESC)
  WHERE campaign_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.campaign_revisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL REFERENCES public.campaigns(id) ON DELETE RESTRICT,
  persona_id uuid NOT NULL REFERENCES public.personas(id) ON DELETE RESTRICT,
  revision integer NOT NULL CHECK (revision > 0),
  audience_id uuid NOT NULL REFERENCES public.audiences(id) ON DELETE RESTRICT,
  campaign_kind text NOT NULL CHECK (campaign_kind IN ('consent_request', 'promotional')),
  purpose text NOT NULL,
  objective text,
  channel text NOT NULL DEFAULT 'whatsapp',
  provider text NOT NULL DEFAULT 'meta_cloud' CHECK (provider IN ('meta_cloud', 'evolution_baileys')),
  graph_version integer,
  graph_checksum text,
  audience_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  content_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  policy_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  policy_checksum text NOT NULL,
  revision_checksum text NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'validated')),
  created_by_user_id uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  reason text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (campaign_id, revision)
);

CREATE INDEX IF NOT EXISTS idx_campaign_revisions_campaign_created
  ON public.campaign_revisions(campaign_id, revision DESC);

CREATE TABLE IF NOT EXISTS public.campaign_revision_imports (
  campaign_revision_id uuid NOT NULL REFERENCES public.campaign_revisions(id) ON DELETE CASCADE,
  import_batch_id uuid NOT NULL REFERENCES public.lead_import_batches(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (campaign_revision_id, import_batch_id)
);

CREATE INDEX IF NOT EXISTS idx_campaign_revision_imports_batch
  ON public.campaign_revision_imports(import_batch_id, campaign_revision_id);

CREATE TABLE IF NOT EXISTS public.campaign_recipients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL REFERENCES public.campaigns(id) ON DELETE CASCADE,
  campaign_revision_id uuid NOT NULL REFERENCES public.campaign_revisions(id) ON DELETE CASCADE,
  campaign_revision integer NOT NULL CHECK (campaign_revision > 0),
  lead_id bigint NOT NULL REFERENCES public.leads(id) ON DELETE RESTRICT,
  persona_id uuid NOT NULL REFERENCES public.personas(id) ON DELETE CASCADE,
  applicable_consent_id uuid REFERENCES public.contact_consents(id) ON DELETE SET NULL,
  consent_status text NOT NULL CHECK (consent_status IN ('pending', 'granted', 'refused', 'revoked', 'review_required', 'unknown')),
  sequence_status text NOT NULL DEFAULT 'selected' CHECK (sequence_status IN (
    'selected', 'eligible', 'blocked', 'queued', 'awaiting_reply',
    'retry_scheduled', 'responded', 'completed', 'cancelled'
  )),
  suppression_status text NOT NULL DEFAULT 'none' CHECK (suppression_status IN (
    'none', 'cooldown', 'unsubscribed', 'policy_blocked', 'manual'
  )),
  contact_status text NOT NULL DEFAULT 'unknown' CHECK (contact_status IN (
    'unknown', 'valid', 'invalid_number', 'provider_blocked'
  )),
  commercial_attempt_count integer NOT NULL DEFAULT 0 CHECK (commercial_attempt_count >= 0),
  unanswered_attempt_count integer NOT NULL DEFAULT 0 CHECK (unanswered_attempt_count >= 0),
  last_commercial_attempt_at timestamptz,
  next_commercial_attempt_at timestamptz,
  blocked_reason text,
  response_message_id bigint REFERENCES public.messages(id) ON DELETE SET NULL,
  response_received_at timestamptz,
  response_attributed_at timestamptz,
  retries_stopped_at timestamptz,
  response_attribution_status text NOT NULL DEFAULT 'none' CHECK (response_attribution_status IN (
    'none', 'attributed', 'outside_window', 'not_correlatable'
  )),
  response_classification text NOT NULL DEFAULT 'none' CHECK (response_classification IN (
    'none', 'other', 'consent_positive', 'consent_negative', 'ambiguous'
  )),
  consent_response_status text NOT NULL DEFAULT 'none' CHECK (consent_response_status IN (
    'none', 'granted', 'refused', 'review_required'
  )),
  qualified_at timestamptz,
  opportunity_at timestamptz,
  converted_at timestamptz,
  policy_checksum text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (campaign_id, campaign_revision, lead_id)
);

CREATE INDEX IF NOT EXISTS idx_campaign_recipients_campaign_status
  ON public.campaign_recipients(campaign_id, campaign_revision, sequence_status);
CREATE INDEX IF NOT EXISTS idx_campaign_recipients_due
  ON public.campaign_recipients(persona_id, next_commercial_attempt_at)
  WHERE sequence_status IN ('eligible', 'retry_scheduled');
CREATE INDEX IF NOT EXISTS idx_campaign_recipients_lead
  ON public.campaign_recipients(persona_id, lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_campaign_recipients_attributed_response
  ON public.campaign_recipients(campaign_id, campaign_revision, response_attributed_at)
  WHERE response_attributed_at IS NOT NULL;

-- Campaign messages share the canonical outbox but remain explicitly scoped.
ALTER TABLE public.lead_buffer
  ADD COLUMN IF NOT EXISTS campaign_id uuid REFERENCES public.campaigns(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS campaign_revision integer,
  ADD COLUMN IF NOT EXISTS campaign_recipient_id uuid REFERENCES public.campaign_recipients(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS message_origin text NOT NULL DEFAULT 'conversation',
  ADD COLUMN IF NOT EXISTS campaign_step integer,
  ADD COLUMN IF NOT EXISTS policy_checksum text,
  ADD COLUMN IF NOT EXISTS provider_attempt_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.lead_buffer DROP CONSTRAINT IF EXISTS lead_buffer_message_origin_check;
ALTER TABLE public.lead_buffer DROP CONSTRAINT IF EXISTS lead_buffer_provider_attempt_count_check;
ALTER TABLE public.lead_buffer DROP CONSTRAINT IF EXISTS lead_buffer_campaign_scope_check;
ALTER TABLE public.lead_buffer
  ADD CONSTRAINT lead_buffer_message_origin_check
  CHECK (message_origin IN ('conversation', 'campaign')),
  ADD CONSTRAINT lead_buffer_provider_attempt_count_check
  CHECK (provider_attempt_count >= 0),
  ADD CONSTRAINT lead_buffer_campaign_scope_check
  CHECK (
    message_origin <> 'campaign'
    OR (
      direction = 'outbound'
      AND campaign_id IS NOT NULL
      AND campaign_revision > 0
      AND campaign_recipient_id IS NOT NULL
      AND campaign_step > 0
      AND NULLIF(policy_checksum, '') IS NOT NULL
    )
  );

CREATE INDEX IF NOT EXISTS idx_lead_buffer_campaign_recipient
  ON public.lead_buffer(campaign_id, campaign_revision, campaign_recipient_id, created_at DESC)
  WHERE message_origin = 'campaign';

ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS campaign_id uuid REFERENCES public.campaigns(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS campaign_revision integer,
  ADD COLUMN IF NOT EXISTS campaign_recipient_id uuid REFERENCES public.campaign_recipients(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS message_origin text NOT NULL DEFAULT 'conversation';

ALTER TABLE public.messages DROP CONSTRAINT IF EXISTS messages_message_origin_check;
ALTER TABLE public.messages DROP CONSTRAINT IF EXISTS messages_campaign_scope_check;
ALTER TABLE public.messages
  ADD CONSTRAINT messages_message_origin_check
  CHECK (message_origin IN ('conversation', 'campaign')),
  ADD CONSTRAINT messages_campaign_scope_check
  CHECK (
    message_origin <> 'campaign'
    OR (
      direction = 'outbound'
      AND campaign_id IS NOT NULL
      AND campaign_revision > 0
      AND campaign_recipient_id IS NOT NULL
    )
  );

CREATE OR REPLACE FUNCTION public.enforce_campaign_scope_integrity_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF TG_TABLE_NAME = 'lead_import_batches' THEN
    IF NEW.audience_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.audiences a
      WHERE a.id = NEW.audience_id
        AND a.persona_id = NEW.persona_id
        AND COALESCE(a.metadata->>'kind', 'semantic_group') = 'semantic_group'
    ) THEN
      RAISE EXCEPTION 'import audience must be a semantic group in the same persona'
        USING ERRCODE = '23514';
    END IF;
  ELSIF TG_TABLE_NAME = 'lead_import_rows' THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.lead_import_batches b
      WHERE b.id = NEW.batch_id AND b.persona_id = NEW.persona_id
    ) OR (
      NEW.lead_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.leads l
        WHERE l.id = NEW.lead_id AND l.persona_id = NEW.persona_id
      )
    ) THEN
      RAISE EXCEPTION 'import row scope mismatch' USING ERRCODE = '23514';
    END IF;
  ELSIF TG_TABLE_NAME = 'contact_consents' THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.leads l
      WHERE l.id = NEW.lead_id AND l.persona_id = NEW.persona_id
    ) OR (
      NEW.campaign_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.campaigns c
        WHERE c.id = NEW.campaign_id AND c.persona_id = NEW.persona_id
      )
    ) OR (
      NEW.import_batch_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.lead_import_batches b
        WHERE b.id = NEW.import_batch_id AND b.persona_id = NEW.persona_id
      )
    ) THEN
      RAISE EXCEPTION 'consent scope mismatch' USING ERRCODE = '23514';
    END IF;
  ELSIF TG_TABLE_NAME = 'campaign_revisions' THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.campaigns c
      WHERE c.id = NEW.campaign_id AND c.persona_id = NEW.persona_id
    ) OR NOT EXISTS (
      SELECT 1 FROM public.audiences a
      WHERE a.id = NEW.audience_id AND a.persona_id = NEW.persona_id
        AND COALESCE(a.metadata->>'kind', 'semantic_group') = 'semantic_group'
    ) THEN
      RAISE EXCEPTION 'campaign revision scope mismatch' USING ERRCODE = '23514';
    END IF;
  ELSIF TG_TABLE_NAME = 'campaign_revision_imports' THEN
    IF NOT EXISTS (
      SELECT 1
      FROM public.campaign_revisions r
      JOIN public.lead_import_batches b ON b.id = NEW.import_batch_id
      WHERE r.id = NEW.campaign_revision_id AND r.persona_id = b.persona_id
    ) THEN
      RAISE EXCEPTION 'campaign import scope mismatch' USING ERRCODE = '23514';
    END IF;
  ELSIF TG_TABLE_NAME = 'campaign_recipients' THEN
    IF NOT EXISTS (
      SELECT 1
      FROM public.campaigns c
      JOIN public.campaign_revisions r
        ON r.id = NEW.campaign_revision_id
       AND r.campaign_id = c.id
       AND r.revision = NEW.campaign_revision
      JOIN public.leads l ON l.id = NEW.lead_id
      WHERE c.id = NEW.campaign_id
        AND c.persona_id = NEW.persona_id
        AND r.persona_id = NEW.persona_id
        AND r.policy_checksum = NEW.policy_checksum
        AND l.persona_id = NEW.persona_id
        AND (
          NEW.applicable_consent_id IS NULL
          OR EXISTS (
            SELECT 1 FROM public.contact_consents cc
            WHERE cc.id = NEW.applicable_consent_id
              AND cc.lead_id = NEW.lead_id
              AND cc.persona_id = NEW.persona_id
          )
        )
    ) THEN
      RAISE EXCEPTION 'campaign recipient scope mismatch' USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_lead_import_batch_scope_v1 ON public.lead_import_batches;
CREATE TRIGGER trg_lead_import_batch_scope_v1
BEFORE INSERT OR UPDATE ON public.lead_import_batches
FOR EACH ROW EXECUTE FUNCTION public.enforce_campaign_scope_integrity_v1();
DROP TRIGGER IF EXISTS trg_lead_import_row_scope_v1 ON public.lead_import_rows;
CREATE TRIGGER trg_lead_import_row_scope_v1
BEFORE INSERT OR UPDATE ON public.lead_import_rows
FOR EACH ROW EXECUTE FUNCTION public.enforce_campaign_scope_integrity_v1();
DROP TRIGGER IF EXISTS trg_contact_consent_scope_v1 ON public.contact_consents;
CREATE TRIGGER trg_contact_consent_scope_v1
BEFORE INSERT OR UPDATE ON public.contact_consents
FOR EACH ROW EXECUTE FUNCTION public.enforce_campaign_scope_integrity_v1();
DROP TRIGGER IF EXISTS trg_campaign_revision_scope_v1 ON public.campaign_revisions;
CREATE TRIGGER trg_campaign_revision_scope_v1
BEFORE INSERT OR UPDATE ON public.campaign_revisions
FOR EACH ROW EXECUTE FUNCTION public.enforce_campaign_scope_integrity_v1();
DROP TRIGGER IF EXISTS trg_campaign_revision_import_scope_v1 ON public.campaign_revision_imports;
CREATE TRIGGER trg_campaign_revision_import_scope_v1
BEFORE INSERT OR UPDATE ON public.campaign_revision_imports
FOR EACH ROW EXECUTE FUNCTION public.enforce_campaign_scope_integrity_v1();
DROP TRIGGER IF EXISTS trg_campaign_recipient_scope_v1 ON public.campaign_recipients;
CREATE TRIGGER trg_campaign_recipient_scope_v1
BEFORE INSERT OR UPDATE ON public.campaign_recipients
FOR EACH ROW EXECUTE FUNCTION public.enforce_campaign_scope_integrity_v1();

CREATE OR REPLACE FUNCTION public.enforce_single_semantic_group_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  v_persona_id uuid;
  v_kind text;
BEGIN
  SELECT a.persona_id, COALESCE(a.metadata->>'kind', 'semantic_group')
  INTO v_persona_id, v_kind
  FROM public.audiences a
  WHERE a.id = NEW.audience_id;

  IF v_kind = 'semantic_group' AND EXISTS (
    SELECT 1
    FROM public.lead_audience_memberships lam
    JOIN public.audiences a ON a.id = lam.audience_id
    WHERE lam.lead_id = NEW.lead_id
      AND a.persona_id = v_persona_id
      AND COALESCE(a.metadata->>'kind', 'semantic_group') = 'semantic_group'
      AND lam.id IS DISTINCT FROM NEW.id
  ) THEN
    RAISE EXCEPTION 'lead already belongs to a semantic group in this persona'
      USING ERRCODE = '23505';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_single_semantic_group_v1 ON public.lead_audience_memberships;
CREATE TRIGGER trg_single_semantic_group_v1
BEFORE INSERT OR UPDATE OF lead_id, audience_id ON public.lead_audience_memberships
FOR EACH ROW EXECUTE FUNCTION public.enforce_single_semantic_group_v1();

CREATE OR REPLACE FUNCTION public.prevent_campaign_immutable_mutation_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000';
END;
$$;

DROP TRIGGER IF EXISTS trg_contact_consents_append_only_v1 ON public.contact_consents;
CREATE TRIGGER trg_contact_consents_append_only_v1
BEFORE UPDATE OR DELETE ON public.contact_consents
FOR EACH ROW EXECUTE FUNCTION public.prevent_campaign_immutable_mutation_v1();

DROP TRIGGER IF EXISTS trg_campaign_revisions_append_only_v1 ON public.campaign_revisions;
CREATE TRIGGER trg_campaign_revisions_append_only_v1
BEFORE UPDATE OR DELETE ON public.campaign_revisions
FOR EACH ROW EXECUTE FUNCTION public.prevent_campaign_immutable_mutation_v1();

CREATE UNIQUE INDEX IF NOT EXISTS idx_system_events_campaign_command_idempotency
  ON public.system_events ((payload->>'idempotency_key'))
  WHERE event_type IN ('campaign_draft_created', 'campaign_paused', 'campaign_cancelled')
    AND NULLIF(payload->>'idempotency_key', '') IS NOT NULL;

CREATE OR REPLACE FUNCTION public.prevent_campaign_audit_mutation_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF OLD.event_type LIKE 'campaign\_%' ESCAPE '\'
     OR OLD.event_type LIKE 'contact\_consent\_%' ESCAPE '\'
     OR OLD.event_type LIKE 'lead\_import\_%' ESCAPE '\'
     OR OLD.event_type = 'lead_semantic_group_changed' THEN
    RAISE EXCEPTION 'campaign audit events are append-only' USING ERRCODE = '55000';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_campaign_audit_append_only_v1 ON public.system_events;
CREATE TRIGGER trg_campaign_audit_append_only_v1
BEFORE UPDATE OR DELETE ON public.system_events
FOR EACH ROW EXECUTE FUNCTION public.prevent_campaign_audit_mutation_v1();

-- Persistence is atomic without coupling the policy gate into one SQL function.
-- Eligibility remains split in the backend; this function only commits a
-- previously evaluated immutable revision and its recipient projection.
CREATE OR REPLACE FUNCTION public.create_campaign_draft_v1(
  p_campaign jsonb,
  p_revision jsonb,
  p_import_ids jsonb,
  p_recipients jsonb,
  p_event jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_campaign_id uuid := (p_campaign->>'id')::uuid;
  v_revision_id uuid := (p_revision->>'id')::uuid;
  v_existing_id uuid;
BEGIN
  SELECT id INTO v_existing_id
  FROM public.campaigns
  WHERE idempotency_key = p_campaign->>'idempotency_key';
  IF v_existing_id IS NOT NULL THEN
    RETURN jsonb_build_object('campaign_id', v_existing_id, 'deduplicated', true);
  END IF;

  INSERT INTO public.campaigns (
    id, persona_id, slug, name, status, format, metadata, created_at, updated_at,
    campaign_kind, purpose, channel, provider, audience_id, current_revision,
    idempotency_key, reason, created_by_user_id
  ) VALUES (
    v_campaign_id, (p_campaign->>'persona_id')::uuid, p_campaign->>'slug',
    p_campaign->>'name', p_campaign->>'status', p_campaign->>'format',
    COALESCE(p_campaign->'metadata', '{}'::jsonb),
    (p_campaign->>'created_at')::timestamptz,
    (p_campaign->>'updated_at')::timestamptz,
    p_campaign->>'campaign_kind', p_campaign->>'purpose', p_campaign->>'channel',
    p_campaign->>'provider', (p_campaign->>'audience_id')::uuid,
    (p_campaign->>'current_revision')::integer, p_campaign->>'idempotency_key',
    p_campaign->>'reason', NULLIF(p_campaign->>'created_by_user_id', '')::uuid
  );

  INSERT INTO public.campaign_revisions (
    id, campaign_id, persona_id, revision, audience_id, campaign_kind, purpose,
    objective, channel, provider, graph_version, graph_checksum,
    audience_snapshot, content_snapshot, policy_snapshot, policy_checksum,
    revision_checksum, status,
    created_by_user_id, reason, created_at
  ) VALUES (
    v_revision_id, v_campaign_id, (p_revision->>'persona_id')::uuid,
    (p_revision->>'revision')::integer, (p_revision->>'audience_id')::uuid,
    p_revision->>'campaign_kind', p_revision->>'purpose', p_revision->>'objective',
    p_revision->>'channel', p_revision->>'provider',
    NULLIF(p_revision->>'graph_version', '')::integer, p_revision->>'graph_checksum',
    COALESCE(p_revision->'audience_snapshot', '{}'::jsonb),
    COALESCE(p_revision->'content_snapshot', '{}'::jsonb),
    COALESCE(p_revision->'policy_snapshot', '{}'::jsonb),
    p_revision->>'policy_checksum', p_revision->>'revision_checksum',
    p_revision->>'status',
    NULLIF(p_revision->>'created_by_user_id', '')::uuid,
    p_revision->>'reason', (p_revision->>'created_at')::timestamptz
  );

  INSERT INTO public.campaign_revision_imports (campaign_revision_id, import_batch_id)
  SELECT v_revision_id, value::uuid
  FROM jsonb_array_elements_text(COALESCE(p_import_ids, '[]'::jsonb));

  INSERT INTO public.campaign_recipients (
    campaign_id, campaign_revision_id, campaign_revision, lead_id, persona_id,
    applicable_consent_id, consent_status, sequence_status, suppression_status,
    contact_status, blocked_reason, policy_checksum
  )
  SELECT
    v_campaign_id, v_revision_id, (p_revision->>'revision')::integer,
    (item->>'lead_id')::bigint,
    (p_campaign->>'persona_id')::uuid,
    NULLIF(item->>'applicable_consent_id', '')::uuid,
    item->>'consent_status', item->>'sequence_status',
    item->>'suppression_status', item->>'contact_status',
    item->>'blocked_reason', p_revision->>'policy_checksum'
  FROM jsonb_array_elements(COALESCE(p_recipients, '[]'::jsonb)) AS item;

  INSERT INTO public.system_events (
    event_type, entity_type, entity_id, persona_id, payload, level, source
  ) VALUES (
    'campaign_draft_created', 'campaign', v_campaign_id,
    (p_campaign->>'persona_id')::uuid, COALESCE(p_event, '{}'::jsonb),
    'info', 'campaigns.create'
  );

  RETURN jsonb_build_object('campaign_id', v_campaign_id, 'deduplicated', false);
END;
$$;

CREATE OR REPLACE FUNCTION public.transition_campaign_status_v1(
  p_campaign_id uuid,
  p_expected_revision integer,
  p_status text,
  p_idempotency_key text,
  p_reason text,
  p_actor_user_id uuid DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_campaign public.campaigns%ROWTYPE;
  v_event_type text;
BEGIN
  IF p_status NOT IN ('paused', 'cancelled') THEN
    RAISE EXCEPTION 'unsupported rollout-one campaign transition' USING ERRCODE = '22023';
  END IF;
  IF NULLIF(btrim(p_idempotency_key), '') IS NULL OR NULLIF(btrim(p_reason), '') IS NULL THEN
    RAISE EXCEPTION 'idempotency key and reason are required' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_campaign
  FROM public.campaigns
  WHERE id = p_campaign_id
  FOR UPDATE;
  IF v_campaign.id IS NULL THEN
    RAISE EXCEPTION 'campaign not found' USING ERRCODE = 'P0002';
  END IF;

  v_event_type := 'campaign_' || p_status;
  IF EXISTS (
    SELECT 1 FROM public.system_events
    WHERE event_type = v_event_type
      AND entity_id::text = p_campaign_id::text
      AND payload->>'idempotency_key' = p_idempotency_key
  ) THEN
    RETURN jsonb_build_object('campaign_id', p_campaign_id, 'deduplicated', true);
  END IF;

  IF v_campaign.current_revision <> p_expected_revision THEN
    RAISE EXCEPTION 'campaign revision conflict' USING ERRCODE = '40001';
  END IF;
  IF v_campaign.status IN ('completed', 'cancelled', 'failed', 'finished') THEN
    RAISE EXCEPTION 'terminal campaign cannot transition' USING ERRCODE = '55000';
  END IF;

  UPDATE public.campaigns
  SET status = p_status, updated_at = now()
  WHERE id = p_campaign_id;

  INSERT INTO public.system_events (
    event_type, entity_type, entity_id, persona_id, payload, level, source
  ) VALUES (
    v_event_type, 'campaign', p_campaign_id, v_campaign.persona_id,
    jsonb_build_object(
      'campaign_revision', p_expected_revision,
      'idempotency_key', p_idempotency_key,
      'reason', p_reason,
      'actor_user_id', p_actor_user_id
    ),
    'info', 'campaigns.status'
  );

  RETURN jsonb_build_object('campaign_id', p_campaign_id, 'deduplicated', false);
END;
$$;

CREATE OR REPLACE FUNCTION public.record_contact_consent_v1(
  p_consent jsonb,
  p_event jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_row public.contact_consents%ROWTYPE;
  v_status text := p_consent->>'status';
BEGIN
  IF v_status NOT IN ('pending', 'granted', 'refused', 'revoked', 'review_required') THEN
    RAISE EXCEPTION 'invalid consent status' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_row
  FROM public.contact_consents
  WHERE idempotency_key = p_consent->>'idempotency_key';
  IF v_row.id IS NOT NULL THEN
    RETURN to_jsonb(v_row) || jsonb_build_object('deduplicated', true);
  END IF;

  INSERT INTO public.contact_consents (
    lead_id, persona_id, channel, purpose, communication_category, status,
    source, request_message_id, response_message_id, campaign_id,
    import_batch_id, effective_at, granted_at, revoked_at, valid_until,
    evidence, actor_user_id, idempotency_key, created_at
  ) VALUES (
    (p_consent->>'lead_id')::bigint,
    (p_consent->>'persona_id')::uuid,
    lower(btrim(p_consent->>'channel')),
    btrim(p_consent->>'purpose'),
    NULLIF(btrim(p_consent->>'communication_category'), ''),
    v_status,
    btrim(p_consent->>'source'),
    NULLIF(p_consent->>'request_message_id', '')::bigint,
    NULLIF(p_consent->>'response_message_id', '')::bigint,
    NULLIF(p_consent->>'campaign_id', '')::uuid,
    NULLIF(p_consent->>'import_batch_id', '')::uuid,
    COALESCE(NULLIF(p_consent->>'effective_at', '')::timestamptz, now()),
    NULLIF(p_consent->>'granted_at', '')::timestamptz,
    NULLIF(p_consent->>'revoked_at', '')::timestamptz,
    NULLIF(p_consent->>'valid_until', '')::timestamptz,
    COALESCE(p_consent->'evidence', '{}'::jsonb),
    NULLIF(p_consent->>'actor_user_id', '')::uuid,
    p_consent->>'idempotency_key',
    COALESCE(NULLIF(p_consent->>'created_at', '')::timestamptz, now())
  ) RETURNING * INTO v_row;

  INSERT INTO public.system_events (
    event_type, entity_type, entity_id, persona_id, payload, level, source
  ) VALUES (
    'contact_consent_' || v_status,
    'lead', v_row.lead_id::text, v_row.persona_id,
    COALESCE(p_event, '{}'::jsonb) || jsonb_build_object('consent_id', v_row.id),
    'info', 'leads.consent'
  );

  RETURN to_jsonb(v_row) || jsonb_build_object('deduplicated', false);
END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_system_events_group_command_idempotency
  ON public.system_events ((payload->>'idempotency_key'))
  WHERE event_type = 'lead_semantic_group_changed'
    AND NULLIF(payload->>'idempotency_key', '') IS NOT NULL;

CREATE OR REPLACE FUNCTION public.replace_lead_semantic_group_v1(
  p_lead_id bigint,
  p_target_persona_id uuid,
  p_audience_id uuid,
  p_created_by_user_id uuid,
  p_idempotency_key text,
  p_reason text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_lead public.leads%ROWTYPE;
  v_audience public.audiences%ROWTYPE;
  v_membership public.lead_audience_memberships%ROWTYPE;
  v_previous_persona_id uuid;
BEGIN
  IF NULLIF(btrim(p_idempotency_key), '') IS NULL OR NULLIF(btrim(p_reason), '') IS NULL THEN
    RAISE EXCEPTION 'idempotency key and reason are required' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_lead FROM public.leads WHERE id = p_lead_id FOR UPDATE;
  IF v_lead.id IS NULL THEN
    RAISE EXCEPTION 'lead not found' USING ERRCODE = 'P0002';
  END IF;
  v_previous_persona_id := v_lead.persona_id;

  SELECT * INTO v_audience FROM public.audiences WHERE id = p_audience_id;
  IF v_audience.id IS NULL
     OR v_audience.persona_id <> p_target_persona_id
     OR COALESCE(v_audience.metadata->>'kind', 'semantic_group') <> 'semantic_group' THEN
    RAISE EXCEPTION 'semantic group not found in target persona' USING ERRCODE = '22023';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.system_events
    WHERE event_type = 'lead_semantic_group_changed'
      AND entity_id = p_lead_id::text
      AND payload->>'idempotency_key' = p_idempotency_key
  ) THEN
    RETURN jsonb_build_object('lead_id', p_lead_id, 'audience_id', p_audience_id, 'deduplicated', true);
  END IF;

  DELETE FROM public.lead_audience_memberships lam
  USING public.audiences a
  WHERE lam.audience_id = a.id
    AND lam.lead_id = p_lead_id
    AND COALESCE(a.metadata->>'kind', 'semantic_group') = 'semantic_group'
    AND a.id <> p_audience_id;

  UPDATE public.leads
  SET persona_id = p_target_persona_id, updated_at = now()
  WHERE id = p_lead_id;

  INSERT INTO public.lead_audience_memberships (
    lead_id, audience_id, membership_type, created_by_user_id
  ) VALUES (
    p_lead_id, p_audience_id, 'primary', p_created_by_user_id
  )
  ON CONFLICT (lead_id, audience_id) DO UPDATE
  SET membership_type = 'primary'
  RETURNING * INTO v_membership;

  INSERT INTO public.system_events (
    event_type, entity_type, entity_id, persona_id, payload, level, source
  ) VALUES (
    'lead_semantic_group_changed', 'lead', p_lead_id::text, p_target_persona_id,
    jsonb_build_object(
      'previous_persona_id', v_previous_persona_id,
      'audience_id', p_audience_id,
      'idempotency_key', p_idempotency_key,
      'reason', p_reason,
      'actor_user_id', p_created_by_user_id
    ),
    'info', 'leads.group'
  );

  RETURN jsonb_build_object(
    'lead_id', p_lead_id,
    'audience_id', p_audience_id,
    'membership_id', v_membership.id,
    'deduplicated', false
  );
END;
$$;

-- All operational campaign data is backend-only. The FastAPI service_role is
-- the sole Data API consumer; browser sessions use the authenticated API.
ALTER TABLE public.lead_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_import_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_revision_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_recipients ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.lead_import_batches FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.lead_import_rows FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.contact_consents FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.campaign_revisions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.campaign_revision_imports FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.campaign_recipients FROM PUBLIC, anon, authenticated;

GRANT ALL ON TABLE public.lead_import_batches TO service_role;
GRANT ALL ON TABLE public.lead_import_rows TO service_role;
GRANT ALL ON TABLE public.contact_consents TO service_role;
GRANT ALL ON TABLE public.campaign_revisions TO service_role;
GRANT ALL ON TABLE public.campaign_revision_imports TO service_role;
GRANT ALL ON TABLE public.campaign_recipients TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.lead_import_rows_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.create_campaign_draft_v1(jsonb, jsonb, jsonb, jsonb, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_campaign_draft_v1(jsonb, jsonb, jsonb, jsonb, jsonb)
  TO service_role;
REVOKE ALL ON FUNCTION public.transition_campaign_status_v1(uuid, integer, text, text, text, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.transition_campaign_status_v1(uuid, integer, text, text, text, uuid)
  TO service_role;
REVOKE ALL ON FUNCTION public.record_contact_consent_v1(jsonb, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_contact_consent_v1(jsonb, jsonb)
  TO service_role;
REVOKE ALL ON FUNCTION public.replace_lead_semantic_group_v1(bigint, uuid, uuid, uuid, text, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.replace_lead_semantic_group_v1(bigint, uuid, uuid, uuid, text, text)
  TO service_role;

NOTIFY pgrst, 'reload schema';
