-- Durable projection and command receipts for the Chatwoot API inbox bridge.
-- The bridge is additive: the existing Meta webhook remains the only source
-- of WhatsApp ingress and the existing transport remains the only sender.

CREATE TABLE IF NOT EXISTS public.chatwoot_bridge_conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_binding_id uuid NOT NULL REFERENCES public.workflow_bindings(id) ON DELETE CASCADE,
  lead_ref bigint NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  account_id bigint NOT NULL,
  inbox_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  contact_identifier text NOT NULL,
  conversation_id bigint,
  last_projected_message_id bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (channel_binding_id, lead_ref),
  UNIQUE (account_id, inbox_id, conversation_id)
);

CREATE TABLE IF NOT EXISTS public.chatwoot_bridge_operations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_kind text NOT NULL CHECK (source_kind IN ('brain_message', 'chatwoot_event')),
  source_id text NOT NULL,
  operation text NOT NULL CHECK (operation IN (
    'project_message', 'human_reply', 'pause_ai', 'resume_ai'
  )),
  channel_binding_id uuid NOT NULL REFERENCES public.workflow_bindings(id) ON DELETE CASCADE,
  lead_ref bigint NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  brain_message_id bigint REFERENCES public.messages(id) ON DELETE CASCADE,
  chatwoot_message_id bigint,
  chatwoot_conversation_id bigint,
  transport_buffer_id uuid REFERENCES public.lead_buffer(id) ON DELETE SET NULL,
  chatwoot_delivery_status text CHECK (chatwoot_delivery_status IN ('sent','delivered','read','failed')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending', 'processing', 'retry', 'completed', 'ignored', 'dead_letter'
  )),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  available_at timestamptz NOT NULL DEFAULT now(),
  locked_at timestamptz,
  locked_by text,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_kind, source_id),
  CHECK (
    (source_kind = 'brain_message' AND brain_message_id IS NOT NULL
      AND operation = 'project_message')
    OR
    (source_kind = 'chatwoot_event' AND brain_message_id IS NULL
      AND operation IN ('human_reply', 'pause_ai', 'resume_ai')
      AND (operation='pause_ai' OR chatwoot_message_id IS NOT NULL))
  )
);

CREATE INDEX IF NOT EXISTS idx_chatwoot_bridge_operations_claim
  ON public.chatwoot_bridge_operations(status, available_at, created_at);
CREATE INDEX IF NOT EXISTS idx_chatwoot_bridge_operations_lead
  ON public.chatwoot_bridge_operations(channel_binding_id, lead_ref, created_at);

ALTER TABLE public.chatwoot_bridge_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chatwoot_bridge_operations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.chatwoot_bridge_conversations FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.chatwoot_bridge_operations FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chatwoot_bridge_conversations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chatwoot_bridge_operations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chatwoot_bridge_conversations TO brain_transport;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chatwoot_bridge_operations TO brain_transport;
GRANT USAGE, SELECT ON SEQUENCE public.chatwoot_bridge_conversations_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.chatwoot_bridge_conversations_id_seq TO brain_transport;

CREATE OR REPLACE FUNCTION public.enqueue_chatwoot_projection_v1(
  p_channel_binding_id uuid,
  p_limit integer DEFAULT 500
) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE
  v_binding public.workflow_bindings%ROWTYPE;
  v_count integer := 0;
BEGIN
  SELECT * INTO v_binding FROM public.workflow_bindings
   WHERE id=p_channel_binding_id AND active=true AND provider='meta_cloud';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'active Meta Cloud binding required' USING ERRCODE='23514';
  END IF;

  INSERT INTO public.chatwoot_bridge_operations(
    source_kind, source_id, operation, channel_binding_id, lead_ref, brain_message_id
  )
  SELECT 'brain_message', m.id::text, 'project_message', p_channel_binding_id,
         l.id, m.id
    FROM public.messages m
    JOIN public.leads l ON l.id=m.lead_id
   WHERE l.channel_binding_id=p_channel_binding_id
     AND (m.direction='inbound'
       OR (m.direction='outbound' AND m.status IN ('sent','delivered','read')))
     AND NOT (m.direction='outbound' AND coalesce(m.metadata,'{}'::jsonb) ? 'chatwoot_message_id')
     AND (m.channel IS NULL OR m.channel='whatsapp')
     AND coalesce(m.metadata->>'validation_transport','false') <> 'true'
     AND NOT EXISTS (
       SELECT 1 FROM public.chatwoot_bridge_operations o
        WHERE o.source_kind='brain_message' AND o.source_id=m.id::text
     )
   ORDER BY m.created_at, m.id
   LIMIT greatest(1,least(coalesce(p_limit,500),2000))
  ON CONFLICT (source_kind,source_id) DO NOTHING;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_chatwoot_bridge_operations_v1(
  p_worker_id text,
  p_limit integer DEFAULT 20,
  p_lease_seconds integer DEFAULT 90
) RETURNS SETOF public.chatwoot_bridge_operations
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  IF nullif(btrim(p_worker_id),'') IS NULL THEN
    RAISE EXCEPTION 'worker id is required' USING ERRCODE='22023';
  END IF;
  -- Serialize claimant selection so two workers cannot claim different
  -- operations for the same lead in the same transaction snapshot.
  PERFORM pg_advisory_xact_lock(hashtext('chatwoot-bridge-claim-v1'));
  RETURN QUERY
  WITH candidates AS (
    SELECT o.id FROM public.chatwoot_bridge_operations o
     WHERE ((o.status IN ('pending','retry') AND o.available_at <= now())
        OR (o.status='processing' AND o.locked_at < now()
            - make_interval(secs => greatest(30,least(coalesce(p_lease_seconds,90),600)))))
       AND NOT EXISTS (
         SELECT 1 FROM public.chatwoot_bridge_operations p
          WHERE p.channel_binding_id=o.channel_binding_id AND p.lead_ref=o.lead_ref
            AND p.status='processing' AND p.id<>o.id
       )
       AND NOT EXISTS (
         SELECT 1 FROM public.chatwoot_bridge_operations q
          WHERE q.channel_binding_id=o.channel_binding_id AND q.lead_ref=o.lead_ref
            AND q.status IN ('pending','retry') AND q.available_at<=now()
            AND NOT (o.operation IN ('pause_ai','resume_ai','human_reply')
                     AND q.operation='project_message')
            AND (q.created_at,q.id)<(o.created_at,o.id)
       )
     ORDER BY CASE WHEN o.operation='project_message' THEN 1 ELSE 0 END,
              o.created_at,o.id
     LIMIT greatest(1,least(coalesce(p_limit,20),100))
     FOR UPDATE OF o SKIP LOCKED
  )
  UPDATE public.chatwoot_bridge_operations o
     SET status='processing', locked_at=now(), locked_by=p_worker_id,
         attempt_count=o.attempt_count+1, updated_at=now()
    FROM candidates c WHERE o.id=c.id
  RETURNING o.*;
END;
$$;

CREATE OR REPLACE FUNCTION public.finish_chatwoot_bridge_operation_v1(
  p_operation_id uuid,
  p_worker_id text,
  p_status text,
  p_error text DEFAULT NULL,
  p_retry_seconds integer DEFAULT 30,
  p_chatwoot_message_id bigint DEFAULT NULL,
  p_chatwoot_conversation_id bigint DEFAULT NULL,
  p_transport_buffer_id uuid DEFAULT NULL
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  IF p_status NOT IN ('completed','ignored','retry','dead_letter') THEN
    RAISE EXCEPTION 'invalid terminal operation status' USING ERRCODE='22023';
  END IF;
  UPDATE public.chatwoot_bridge_operations
     SET status=p_status,
         last_error=left(nullif(p_error,''),500),
         chatwoot_message_id=coalesce(p_chatwoot_message_id,chatwoot_message_id),
         chatwoot_conversation_id=coalesce(p_chatwoot_conversation_id,chatwoot_conversation_id),
         transport_buffer_id=coalesce(p_transport_buffer_id,transport_buffer_id),
         available_at=CASE WHEN p_status='retry'
           THEN now()+make_interval(secs=>greatest(5,least(coalesce(p_retry_seconds,30),3600)))
           ELSE available_at END,
         locked_at=NULL, locked_by=NULL, updated_at=now()
   WHERE id=p_operation_id AND status='processing' AND locked_by=p_worker_id;
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.enqueue_chatwoot_command_v1(
  p_source_id text,
  p_operation text,
  p_channel_binding_id uuid,
  p_lead_ref bigint,
  p_chatwoot_message_id bigint,
  p_chatwoot_conversation_id bigint
) RETURNS public.chatwoot_bridge_operations
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE
  v_row public.chatwoot_bridge_operations%ROWTYPE;
BEGIN
  IF p_operation NOT IN ('human_reply','pause_ai','resume_ai')
     OR nullif(btrim(p_source_id),'') IS NULL THEN
    RAISE EXCEPTION 'invalid Chatwoot command' USING ERRCODE='22023';
  END IF;
  INSERT INTO public.chatwoot_bridge_operations(
    source_kind,source_id,operation,channel_binding_id,lead_ref,
    chatwoot_message_id,chatwoot_conversation_id
  ) VALUES (
    'chatwoot_event',p_source_id,p_operation,p_channel_binding_id,p_lead_ref,
    p_chatwoot_message_id,p_chatwoot_conversation_id
  ) ON CONFLICT (source_kind,source_id) DO NOTHING;
  SELECT * INTO v_row FROM public.chatwoot_bridge_operations
   WHERE source_kind='chatwoot_event' AND source_id=p_source_id;
  IF v_row.channel_binding_id IS DISTINCT FROM p_channel_binding_id
     OR v_row.lead_ref IS DISTINCT FROM p_lead_ref
     OR v_row.operation IS DISTINCT FROM p_operation THEN
    RAISE EXCEPTION 'Chatwoot event id was reused for a different operation' USING ERRCODE='23505';
  END IF;
  RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.enqueue_chatwoot_projection_v1(uuid,integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.claim_chatwoot_bridge_operations_v1(text,integer,integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.finish_chatwoot_bridge_operation_v1(uuid,text,text,text,integer,bigint,bigint,uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.enqueue_chatwoot_command_v1(text,text,uuid,bigint,bigint,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_chatwoot_projection_v1(uuid,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_chatwoot_bridge_operations_v1(text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.finish_chatwoot_bridge_operation_v1(uuid,text,text,text,integer,bigint,bigint,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_chatwoot_command_v1(text,text,uuid,bigint,bigint,bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_chatwoot_projection_v1(uuid,integer) TO brain_transport;
GRANT EXECUTE ON FUNCTION public.claim_chatwoot_bridge_operations_v1(text,integer,integer) TO brain_transport;
GRANT EXECUTE ON FUNCTION public.finish_chatwoot_bridge_operation_v1(uuid,text,text,text,integer,bigint,bigint,uuid) TO brain_transport;
GRANT EXECUTE ON FUNCTION public.enqueue_chatwoot_command_v1(text,text,uuid,bigint,bigint,bigint) TO brain_transport;

NOTIFY pgrst, 'reload schema';
